name: petstagram
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.1.0
  provider: ^6.0.5
  image_picker: ^0.8.7+4
  flutter_svg: ^2.0.7
  uuid: ^3.0.7
  intl: ^0.18.0
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
