name: petstagram
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0          # Added firebase_core for Firebase initialization
  cloud_firestore: ^4.17.5        # Added cloud_firestore for Firestore integration

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
